#!/usr/bin/env ruby

arg_list = ARGV.map { |x| "\"#{x}\"" }.join(" ")
arg_list = Dir["samples/*"] if arg_list.empty?

puts ":: #{arg_list}"
exec %{ruby -I lib ./bin/clean_tape --verbose #{arg_list}}

